#!/usr/bin/env python3
"""
Build grammar_features.json with exactly the 189 Ziems Multi-Value paper features.
Output: shared/grammar_features.json (replaces file; no merge with existing).
"""
import json
from pathlib import Path

# Exactly 189 paper features: id, name, description, example_std, example_var, category
# Categories: pronominal, nominal, verbal, negation, morphosyntactic, agreement, relativization, complementation, adverbial, discourse
PAPER_FEATURES_189 = [
    # Table 7 Pronouns
    ("she_inanimate_objects", "She for inanimate", "Use of 'she' for inanimate objects", "It's a good bike", "She's a good bike", "pronominal"),
    ("he_inanimate_objects", "He for inanimate", "Use of 'him' for inanimate objects", "The driver's license? She wasn't allowed to renew it right?", "The driver's license? She wasn't allowed to renew 'im right?", "pronominal"),
    ("referential_thing", "Referential 'the thing'", "Use of 'the thing' for referential it", "Christmas dinner? I think it's better to wait until after she's had it.", "Christmas dinner? I think it's better to wait until after she's had the thing.", "pronominal"),
    ("pleonastic_that", "Pleonastic that", "It's raining -> Thass raining", "It's raining.", "Thass raining.", "pronominal"),
    ("em_subj_pronoun", "'em subject pronoun", "Use of 'em as subject", "This old woman, she started packing up.", "This old woman, 'em started packing up.", "pronominal"),
    ("em_obj_pronoun", "'em object pronoun", "Use of 'im/'em as object", "We just turned it around.", "We just turned 'im around.", "pronominal"),
    ("me_coordinate_subjects", "Me in coordinate subjects", "Me and X for coordinate subjects", "Michelle and I will come too.", "Me and Michelle will come too.", "pronominal"),
    ("myself_coordinate_subjects", "Myself in coordinate subjects", "X and myself for coordinate subjects", "My husband and I were late.", "My husband and myself were late.", "pronominal"),
    ("benefactive_dative", "Benefactive dative", "Get me one of those", "I have to get one of those!", "I have to get me one of those!", "pronominal"),
    ("no_gender_distinction", "No gender distinction", "He for she in IndE", "Susan is a nurse but she does not like to put drips on patients.", "Susan is a nurse but he does not like to put drips on patients.", "pronominal"),
    ("regularized_reflexives", "Regularized reflexives hisself", "Himself -> hisself", "He hurt himself.", "He hurt hisself.", "pronominal"),
    ("regularized_reflexives_object_pronouns", "Regularized reflexives meself", "Myself -> meself", "I'll do it myself.", "I'll do it meself.", "pronominal"),
    ("regularized_reflexives_aave", "Regularized reflexives theyselves", "Themselves -> theyselves", "They look after themselves.", "They look after theyselves.", "pronominal"),
    ("reflex_number", "Reflexive number ourself", "Ourselves -> ourself", "We cannot change ourselves.", "We cannot change ourself.", "pronominal"),
    ("absolute_reflex", "Absolute reflex himself", "Himself in subject position", "and he and the bull were tuggin' and wrestlin'", "and himself and the bull were tuggin' and wrestlin'", "pronominal"),
    ("emphatic_reflex", "Emphatic reflex their own self", "Themselves -> their own self", "They brought it by themselves.", "They brought it by their own self.", "pronominal"),
    ("my_i", "My -> I (possessive)", "my book -> I book", "my book", "I book", "pronominal"),
    ("our_we", "Our -> we (possessive)", "our farm -> we farm", "our farm", "we farm", "pronominal"),
    ("his_he", "His -> he (possessive)", "his book -> he book", "his book", "he book", "pronominal"),
    ("their_they", "Their -> they (possessive)", "their book -> they book", "their book", "they book", "pronominal"),
    ("your_you", "Your -> you (possessive)", "your book -> you book", "your book", "you book", "pronominal"),
    ("your_yalls", "Your -> y'all's", "Where are your books? -> y'all's books", "Where are your books?", "Where are y'all's books?", "pronominal"),
    ("his_him", "His -> him (possessive)", "his book -> him book", "his book", "him book", "pronominal"),
    ("their_them", "Their -> them (possessive)", "their book -> them book", "their book", "them book", "pronominal"),
    ("my_me", "My -> me (possessive)", "my book -> me book", "my book", "me book", "pronominal"),
    ("our_us", "Our -> us (possessive)", "our book -> us book", "our book", "us book", "pronominal"),
    ("me_us", "Me -> us (object)", "Show me -> Show us", "Show me the town!", "Show us the town!", "pronominal"),
    ("non_coordinated_subj_obj", "Non-coordinated subj/obj with we", "with us -> with we", "Do you want to come with us?", "Do you want to come with we?", "pronominal"),
    ("non_coordinated_obj_subj", "Non-coordinated obj/subj them", "They -> Them as subject", "They can ride all day.", "Them can ride all day.", "pronominal"),
    ("nasal_possessive_pron", "Nasal possessive pronoun", "hers -> hern, hisn, ourn", "her, his, our; hers, ours, ours", "hern, hisn, ourn; hersn, oursn, ourns", "pronominal"),
    ("yall", "Y'all", "you -> y'all", "you", "y'all", "pronominal"),
    ("you_ye", "You -> ye", "to you -> to ye", "Sure it's no good to you in England.", "Sure it's no good to ye in England.", "pronominal"),
    ("plural_interrogative", "Plural interrogative who-all", "Who came? -> Who-all came?", "Who came?", "Who-all came?", "pronominal"),
    ("reduplicate_interrogative", "Reduplicate interrogative", "Who's coming -> Who-who's coming", "Who's coming today?", "Who-who's coming today?", "pronominal"),
    ("anaphoric_it", "Anaphoric it", "they -> it (anaphoric)", "Things have become more expensive than they used to be.", "Things have become more expensive than it used to be.", "pronominal"),
    ("object_pronoun_drop", "Object pronoun drop", "I got it -> I got", "I got it from the store.", "I got from the store.", "pronominal"),
    ("null_referential_pronouns", "Null referential pronouns", "Drop subject pronoun", "When I come back from my work I just travel back to my home.", "When I come back from my work just travel back to my home.", "pronominal"),
    ("it_dobj", "It as direct object", "Add it as dobj", "As I explained to her, this is not the right way.", "As I explained it to her, this is not the right way.", "pronominal"),
    ("it_is_referential", "It is referential drop", "It is very nice -> Is very nice", "It is very nice food.", "Is very nice food.", "pronominal"),
    ("it_is_non_referential", "It is non-referential drop", "it's time -> is time", "Okay, it's time for lunch.", "Okay, is time for lunch.", "pronominal"),
    # Table 8 Noun Phrases
    ("regularized_plurals", "Regularized plurals", "wives -> wifes, knives -> knifes", "wives, knives, lives, leaves", "wifes, knifes, lifes, leafs", "nominal"),
    ("mass_noun_plurals", "Mass noun plurals", "furniture -> furnitures", "furniture, machinery, equipment, evidence, luggage, advice, mail, staff", "furnitures, machineries, equipments, evidences, luggages, advices, mails, staffs", "nominal"),
    ("zero_plural_after_quantifier", "Zero plural after quantifier", "five miles -> five mile", "It's only five miles away.", "It's only five mile away.", "nominal"),
    ("plural_to_singular_human", "Plural to singular human", "three girls -> three girl", "The three girls there don't want to talk to us.", "The three girl there don't want to talk to us.", "nominal"),
    ("zero_plural", "Zero plural", "apartments -> apartment", "Some apartments are bigger.", "Some apartment are bigger.", "nominal"),
    ("double_determiners", "Double determiners", "This common problem of ours -> This our common problem", "This common problem of ours is very serious.", "This our common problem is very serious.", "nominal"),
    ("definite_for_indefinite_articles", "Definite for indefinite", "a toothache -> the toothache", "She's got a toothache.", "She's got the toothache", "nominal"),
    ("indefinite_for_definite_articles", "Indefinite for definite", "The moon -> A moon", "The moon was very bright last night.", "A moon was very bright last night.", "nominal"),
    ("remove_det_definite", "Remove definite article", "in the office -> in office", "He's in the office.", "He's in office.", "nominal"),
    ("remove_det_indefinite", "Remove indefinite article", "a better grade -> better grade", "Can I get a better grade?", "Can I get better grade?", "nominal"),
    ("definite_abstract", "Definite with abstract", "until Christmas -> until the Christmas", "I stayed on until Christmas.", "I stayed on until the Christmas.", "nominal"),
    ("indefinite_for_zero", "Indefinite for zero", "good news -> a good news", "We received good news at last.", "We received a good news at last.", "nominal"),
    ("indef_one", "Indefinite one", "a dog -> one dog", "What happened? Oh, a dog bit me.", "What happened? Oh, one dog bit me.", "nominal"),
    ("demonstrative_for_definite_articles", "Demonstrative for definite", "The elder girl -> That elder girl", "They have two children. The elder girl is 19 years old.", "They have two children. That elder girl is 19 years old.", "nominal"),
    ("those_them", "Those -> them (demonstrative)", "those qualifications -> them qualifications", "I don't have any of those qualifications.", "I don't have any of them qualifications.", "nominal"),
    ("proximal_distal_demonstratives", "Proximal distal demonstratives", "this here book, them there books", "this book that is right here vs. those books that are over there", "this here book vs. them there books", "nominal"),
    ("demonstrative_no_number", "Demonstrative no number", "These books -> This books", "These books are useful for my study.", "This books are useful for my study.", "nominal"),
    ("existential_possessives", "Existential possessives", "I have a son -> Son is there.", "I have a son.", "Son is there.", "nominal"),
    ("possessives_for_post", "Possessives for post", "my mother's house -> the house for my mother", "This is my mother's house.", "This is the house for my mother.", "nominal"),
    ("possessives_for_pre", "Possessives for pre", "my sister's husband -> for my sister husband", "Long time ago he was my sister's husband.", "Long time he was for my sister husband.", "nominal"),
    ("possessives_belong", "Possessives belong", "the woman's friend -> woman belong friend", "the woman's friend", "woman belong friend", "nominal"),
    ("null_genitive", "Null genitive", "my cousin's bike -> my cousin bike", "my cousin's bike", "my cousin bike", "nominal"),
    ("double_comparative", "Double comparative", "easier -> more easier", "That is so much easier to follow.", "That is so much more easier to follow.", "nominal"),
    ("double_superlative", "Double superlative", "most X -> most most X", "He is the most regular guy I know.", "He is the most most regular guy I know.", "nominal"),
    ("synthetic_superlative", "Synthetic superlative", "most regular -> regularest", "He is the most regular guy I know.", "He is the regularest guy I know.", "nominal"),
    ("analytic_superlative", "Analytic superlative", "prettiest -> most pretty", "one of the prettiest sunsets", "one of the most pretty sunsets", "nominal"),
    ("more_much", "More -> much", "more serious -> much serious", "The situation is more serious than I thought.", "The situation is much serious than I thought.", "nominal"),
    ("comparative_as_to", "Comparative as to", "bigger than -> bigger as", "She is bigger than her sister.", "She is bigger as her sister.", "nominal"),
    ("comparative_than", "Comparative than", "more than -> than", "They like football more than basketball.", "They like football than basketball.", "nominal"),
    ("comparative_more_and", "Comparative more and", "than all -> and all", "He has more clothes than all of us.", "He has more clothes and all of us.", "nominal"),
    ("zero_degree", "Zero degree", "most radical -> radical", "He is one of the most radical students that you can ever find.", "He is one of the radical students that you can ever find.", "nominal"),
    ("adj_postfix", "Adjective postfix", "A big and fresh fish -> A fish big and fresh", "A big and fresh fish is my favorite.", "A fish big and fresh is my favorite.", "nominal"),
    # Table 9 Tense and Aspect
    ("progressives", "Progressives", "I like -> I am liking", "I like her hair style right now.", "I am liking her hair style.", "verbal"),
    ("standing_stood", "Standing -> stood", "was standing -> was stood", "He was standing on the corner.", "He was stood on the corner.", "verbal"),
    ("that_resultative_past_participle", "That resultative past participle", "that broke down -> broken down", "There is a car that broke down on the road.", "There is a car broken down on the road.", "verbal"),
    ("medial_object_perfect", "Medial object perfect", "He has written a letter -> He has a letter written", "He has written a letter.", "He has a letter written.", "verbal"),
    ("after_perfect", "After perfect", "has just sold -> after selling", "She has just sold the boat.", "She's after selling the boat.", "verbal"),
    ("simple_past_for_present_perfect", "Simple past for present perfect", "I've eaten -> I ate", "I've eaten the food. So can I go now?", "I ate the food. So can I go now?", "verbal"),
    ("present_perfect_for_past", "Present perfect for past", "We were there -> We've been there", "We were there last year.", "We've been there last year.", "verbal"),
    ("present_for_exp_perfect", "Present for experiential perfect", "I've known -> I know", "I've known her since she was a child.", "I know her since she was a child.", "verbal"),
    ("be_perfect", "Be perfect", "haven't left -> not left", "They haven't left school yet.", "They're not left school yet.", "verbal"),
    ("do_tense_marker", "Do tense marker", "I knew -> I did know", "I knew some things weren't right.", "I did know some things weren't right.", "verbal"),
    ("completive_done", "Completive done", "She has already left -> She done left", "She has already left", "She done left", "verbal"),
    ("completive_have_done", "Completive have done", "has talked -> has done talked", "He has talked about me.", "He has done talked about me.", "verbal"),
    ("irrealis_be_done", "Irrealis be done", "they will eat -> they be done eat", "If you love your enemies, they will eat you alive in this society.", "If you love your enemies, they be done eat you alive in this society.", "verbal"),
    ("perfect_slam", "Perfect slam", "I have already told -> I slam told", "I have already told you not to mess up", "I slam told you not to mess up.", "verbal"),
    ("present_perfect_ever", "Present perfect ever", "I have seen -> I ever see", "I have seen the movie.", "I ever see the movie.", "verbal"),
    ("perfect_already", "Perfect already", "Have you eaten -> Did you eat already?", "Have you eaten lunch?", "Did you eat already?", "verbal"),
    ("completive_finish", "Completive finish", "I have eaten -> I finish eat", "I have eaten.", "I finish eat.", "verbal"),
    ("past_been", "Past been", "I told you -> I been told you", "I told you.", "I been told you.", "verbal"),
    ("bare_perfect", "Bare perfect", "had caught -> had catch", "We had caught the fish when the big wave hit.", "We had catch the fish when the big wave hit.", "verbal"),
    ("future_sub_gon", "Future sub gon", "He will come -> He gon' come", "He will come with us.", "He gon' come with us.", "verbal"),
    ("volition_changes", "Volition changes", "You want to go -> You waan go", "You want to go.", "You waan go.", "verbal"),
    ("come_future", "Come future", "I am about to cook -> I am coming to cook", "I am about to cook your meal.", "I am coming to cook your meal.", "verbal"),
    ("present_for_neutral_future", "Present for neutral future", "I will be leaving -> I leaving", "Next week, I will be leaving the States and going to Liberia.", "Next week, I leaving the States, I going to Liberia.", "verbal"),
    ("is_am_1s", "Is/am 1s", "I am going -> I's going", "I am going to town.", "I's going to town.", "verbal"),
    ("will_would", "Will -> would", "I will meet -> I would meet", "I will meet him tomorrow.", "I would meet him tomorrow.", "verbal"),
    ("if_would", "If would", "If I were you -> If I would be you", "If I were you I would go home now.", "If I would be you I would go home now.", "verbal"),
    # Table 10 Mood
    ("double_modals", "Double modals", "We could do -> We might could do", "We could do that.", "We might could do that.", "verbal"),
    ("present_modals", "Present modals", "I wish I could -> I wish I can", "I wish I could get the job.", "I wish I can get the job.", "verbal"),
    ("finna_future", "Finna/fixin future", "They're about to leave -> They're fixin to leave", "They're about to leave.", "They're fixin to leave town.", "verbal"),
    ("fixin_future", "Fixin future", "about to/going to -> fixin to", "They're going to leave.", "They're fixin to leave.", "verbal"),
    # Table 11 Verb Morphology
    ("regularized_past_tense", "Regularized past tense", "He caught -> He catched", "He caught the ball.", "He catched the ball.", "verbal"),
    ("bare_past_tense", "Bare past tense", "They came -> They come", "They came and joined us.", "They come and joined us.", "verbal"),
    ("past_for_past_participle", "Past for past participle", "had gone -> had went", "He had gone.", "He had went.", "verbal"),
    ("participle_past_tense", "Participle past tense", "I saw it -> I seen it", "I saw it.", "I seen it.", "verbal"),
    ("double_past", "Double past", "didn't make -> didn't made", "They didn't make it this time.", "They didn't made it this time.", "verbal"),
    ("conditional_were_was", "Conditional were/was", "If I were you -> If I was you", "If I were you I would go home now.", "If I was you I would go home now.", "verbal"),
    ("a_ing", "A-prefix -ing", "you going -> you a-goin?", "Where are you going?", "Where are you a-goin?", "verbal"),
    ("a_participle", "A-prefix participle", "You've killed -> You've a-killed", "You've killed your mother.", "You've a-killed your mother.", "verbal"),
    ("transitive_suffix", "Transitive suffix", "see the fish -> see 'im fish", "You can see the fish.", "You can see 'im fish.", "verbal"),
    ("got_gotten", "Got -> gotten", "you've got -> you've gotten", "I hope you've got your topic already.", "I hope you've gotten your topic already.", "verbal"),
    ("verbal_ing_suffix", "Verbal -ing suffix", "I can drive -> I can driving", "I can drive now.", "I can driving now.", "verbal"),
    ("serial_verb_give", "Serial verb give", "I bought rice for you -> I buy rice give you", "I bought rice for you.", "I buy rice give you.", "verbal"),
    ("serial_verb_go", "Serial verb go", "sends us to school -> send us go school", "Grandfather sends us to school.", "Grandfather send us go school.", "verbal"),
    ("here_come", "Here come", "Bring the book here -> Take the book bring come", "Bring the book here.", "Take the book bring come.", "verbal"),
    ("give_passive", "Give passive", "John was scolded by his boss -> John give his boss scold", "John was scolded by his boss", "John give his boss scold.", "verbal"),
    # Table 12 Negation
    ("negative_concord", "Negative concord", "don't have anything -> don't have nothing", "I don't have anything", "I don't have nothing", "negation"),
    ("aint_be", "Ain't for be", "is not -> ain't", "She is not going.", "She ain't going.", "negation"),
    ("aint_have", "Ain't for have", "have not -> ain't", "I have not seen it.", "I ain't seen it.", "negation"),
    ("aint_before_main", "Ain't before main verb", "did not -> ain't", "He did not tell me.", "He ain't tell me.", "negation"),
    ("dont", "Invariant don't", "he doesn't -> he don't", "He doesn't always tell the truth", "He don't always tell the truth", "negation"),
    ("never_negator", "Never as negator", "didn't come -> never came", "He didn't come", "He never came", "negation"),
    ("no_preverbal_negator", "No preverbal negator", "I don't want -> I no want", "I don't want any job or anything.", "I no want any job or anything.", "negation"),
    ("not_preverbal_negator", "Not preverbal negator", "didn't eat -> not ate", "The baby didn't eat food and cried a lot.", "The baby not ate food and cried a lot.", "negation"),
    ("nomo_existential", "Nomo existential", "There is not any food -> No more food", "There is not any food in the refrigerator.", "No more food in the refrigerator.", "negation"),
    ("wasnt_werent", "Wasn't/weren't leveling", "Mike wasn't -> Mike weren't", "John was there, but Mike wasn't", "John was there, but Mike weren't", "negation"),
    ("invariant_tag_amnt", "Invariant tag amn't I", "Is that correct? -> amn't I?", "I believe I am older than you. Is that correct?", "I am older than you, amn't I?", "negation"),
    ("invariant_tag_non_concord", "Invariant tag non-concord", "Is that correct? -> isn't it?", "I believe you are ill. Is that correct?", "You are ill, isn't it?", "negation"),
    ("invariant_tag_can_or_not", "Invariant tag can or not", "Can I go home? -> I want to go home, can or not?", "Can I go home?", "I want to go home, can or not?", "negation"),
    ("invariant_tag_fronted_isnt", "Invariant tag fronted isn't", "can't I? -> Isn't, I can go there now?", "I can go there now can't I?", "Isn't, I can go there now?", "negation"),
    # Table 13 Agreement
    ("existential_there", "Existential there (singular agreement)", "There are -> There's (with plural)", "There are two men waiting", "There's two men waiting", "verbal"),
    ("existential_it", "Existential it", "There is -> It's", "There is a problem", "It's a problem", "verbal"),
    ("uninflect", "Uninflect", "He speaks -> He speak", "He speaks English.", "He speak English.", "verbal"),
    ("generalized_third_person_s", "Generalized third person -s", "we go -> we goes", "Every Sunday we go to church.", "Every Sunday we goes to church.", "verbal"),
    ("drop_aux_be_progressive", "Drop aux be progressive", "You are always thinking -> You always thinking", "You are always thinking about it.", "You always thinking about it.", "verbal"),
    ("drop_aux_be_gonna", "Drop aux be gonna", "He is gonna -> He gonna", "He is gonna go home and watch TV.", "He gonna go home and watch TV.", "verbal"),
    ("drop_copula_be_NP", "Drop copula be NP", "He is a good teacher -> He a good teacher", "He is a good teacher.", "He a good teacher.", "verbal"),
    ("drop_copula_be_AP", "Drop copula be AP", "She is smart -> She smart", "She is smart.", "She smart.", "verbal"),
    ("drop_copula_be_locative", "Drop copula be locative", "She is at home -> She at home", "She is at home.", "She at home.", "verbal"),
    ("drop_aux_have", "Drop aux have", "I have seen -> I seen", "I have seen it before.", "I seen it before.", "verbal"),
    ("were_was", "Were/was leveling", "You were -> You was", "You were hungry but he was thirsty.", "You was hungry but he was thirsty.", "verbal"),
    # Table 14 Relativization
    ("who_which", "Who/which", "the man who -> the man which", "He's the man who looks after the cows.", "He's the man which looks after the cows.", "morphosyntactic"),
    ("who_as", "Who/as", "The man who -> The man as", "The man who was just here.", "The man as was just here.", "morphosyntactic"),
    ("who_at", "Who/at", "the man who -> the man at", "This is the man who painted my house.", "This is the man at painted my house.", "morphosyntactic"),
    ("relativizer_where", "Relativizer where", "which helped -> where help", "My father was one of the founders of the Underground Railroad, which helped the slaves to run away to the North", "My father was one o de founders o' de Underground Railroad where help de slaves to run way to de North.", "morphosyntactic"),
    ("who_what", "Who/what", "the man who -> the man what", "This is the man who painted my house.", "This is the man what painted my house.", "morphosyntactic"),
    ("relativizer_doubling", "Relativizer doubling", "who had stayed -> that which had stayed", "But these, these little fellahs who had stayed before", "But these, these little fellahs that which had stayed befo'", "morphosyntactic"),
    ("analytic_whose_relativizer", "Analytic whose relativizer", "whose wife -> that his wife", "This is the man whose wife has died.", "This is the man that his wife has died.", "morphosyntactic"),
    ("null_relcl", "Null relative clause", "The man who lives -> The man lives", "The man who lives there is friendly.", "The man lives there is friendly.", "morphosyntactic"),
    ("shadow_pronouns", "Shadow pronouns", "which I painted -> which I painted it", "This is the house which I painted yesterday.", "This is the house which I painted it yesterday.", "morphosyntactic"),
    ("one_relativizer", "One relativizer", "The cake that John buys -> The cake John buy one", "The cake that John buys is always very nice to eat.", "The cake John buy one always very nice to eat.", "morphosyntactic"),
    ("correlative_constructions", "Correlative constructions", "The ones I made are the good ones -> The one I made, that one is good", "The ones I made are the good ones.", "The one I made, that one is good.", "morphosyntactic"),
    ("linking_relcl", "Linking relative clause", "but some universities -> which some universities", "Unless you are going to get 88, but some universities are not going to give those marks", "Unless you are going to get 88 which some universities are not going to give those marks", "morphosyntactic"),
    ("preposition_chopping", "Preposition chopping", "sit together on? -> sit together?", "You remember the swing that we all used to sit together on?", "You remember the swing that we all used to sit together?", "morphosyntactic"),
    ("reduced_relative", "Reduced relative", "food cooked by Amma -> Amma cooked food", "There is nothing like food cooked by Amma!", "There is nothing like Amma cooked food!", "morphosyntactic"),
    # Table 15 Complementation
    ("say_complementizer", "Say complementizer", "We hear that -> We hear say", "We hear that you were gone to the city.", "We hear say you gone to the city.", "verbal"),
    ("for_complementizer", "For complementizer", "allows you to bring -> allows you for bring", "You mean your mother allows you to bring over boyfriends?", "You mean your mother allows you for bring over boyfriends?", "verbal"),
    ("for_to_purpose", "For to purpose", "to drain -> for to drain", "We always had gutters in the winter time to drain the water away.", "We always had gutters in the winter time for to drain the water away.", "verbal"),
    ("for_to", "For to", "the privilege to turn -> the privilege for to turn", "He had the privilege to turn on the lights.", "He had the privilege for to turn on the lights.", "verbal"),
    ("what_comparative", "What comparative", "taller than he is -> taller than what he is", "I'm taller than he is.", "I'm taller than what he is.", "verbal"),
    ("existential_got", "Existential got", "There's no water -> Got no water", "There's no water in the toilet.", "Got no water in the toilet.", "verbal"),
    ("existential_you_have", "Existential you have", "There are some people -> You have some people", "There are some people who don't give a damn about animals.", "You have some people they don't give a damn about animals.", "verbal"),
    ("that_infinitival_subclause", "That infinitival subclause", "He wanted me to go -> He wanted that I should go", "He wanted me to go with him.", "He wanted that I should go with him.", "verbal"),
    ("drop_inf_to", "Drop inf to", "allowed to call -> allowed call", "They were allowed to call her.", "They were allowed call her.", "verbal"),
    ("to_infinitive", "To infinitive", "He made me do -> He made me to do", "He made me do it.", "He made me to do it.", "verbal"),
    ("bare_ccomp", "Bare ccomp", "started whooping -> started whoop", "When mistress started whooping her, she sat her down.", "When mistress started whoop her, she sat her down.", "verbal"),
    # Table 16 Adverbial
    ("clause_final_though_but", "Clause final though/but", "this box though -> this box, but", "There's nothing wrong with this box though.", "There's nothing wrong with this box, but.", "morphosyntactic"),
    ("clause_final_really_but", "Clause final really/but", "she can do, really -> she can do, but", "I don't know what else she can do, really.", "I don't know what else she can do, but.", "morphosyntactic"),
    ("chaining_main_verbs", "Chaining main verbs", "If you stay longer, they have to charge -> Stay longer, they have to over-charge", "If you stay longer, they have to charge more.", "Stay longer, they have to over-charge.", "morphosyntactic"),
    ("corr_conjunction_doubling", "Correlative conjunction doubling", "he still made -> still yet he made", "Despite being instructed on what to do, he still made some mistakes.", "Despite being instructed on what to do still yet he made some mistakes.", "morphosyntactic"),
    ("subord_conjunction_doubling", "Subord conjunction doubling", "Although you are smart, you are not -> Although you are smart, but you are not", "Although you are smart, you are not appreciated", "Although you are smart, but you are not appreciated", "morphosyntactic"),
    # Table 17 Adverbs and Prepositions
    ("null_prepositions", "Null prepositions", "going to town -> going town", "I'm going to town.", "I'm going town.", "morphosyntactic"),
    ("degree_adj_for_adv", "Degree adj for adv", "really nice -> real nice", "That's really nice and cold", "That's real nice and cold", "morphosyntactic"),
    ("flat_adj_for_adv", "Flat adj for adv", "speaks softly -> speaks soft", "She speaks so softly.", "She speaks so soft.", "morphosyntactic"),
    ("too_sub", "Too sub", "very nice -> too nice", "They are very nice. We had a good time there.", "They are too nice. We had a good time there.", "morphosyntactic"),
    # Table 18 Discourse
    ("clefting", "Clefting", "A lot of them are looking -> It's looking for more land a lot of them are", "A lot of them are looking for more land.", "It's looking for more land a lot of them are.", "discourse"),
    ("fronting_pobj", "Fronting pobj", "I drive to town every Saturday -> To town every Saturday I drive", "I drive to town every Saturday.", "To town every Saturday I drive.", "discourse"),
    ("negative_inversion", "Negative inversion", "Nobody showed up -> Didn't nobody show up", "Nobody showed up.", "Didn't nobody show up.", "discourse"),
    ("inverted_indirect_question", "Inverted indirect question", "what you are going to do -> what are you going to do", "I'm wondering what you are going to do.", "I'm wondering what are you going to do.", "discourse"),
    ("drop_aux_wh", "Drop aux wh", "When is she coming? -> When she coming?", "When is she coming?", "When she coming?", "discourse"),
    ("drop_aux_yn", "Drop aux yn", "Do you get the point? -> You get the point?", "Do you get the point?", "You get the point?", "discourse"),
    ("doubly_filled_comp", "Doubly filled comp", "Who ate what? -> What who has eaten?", "Who ate what?", "What who has eaten?", "discourse"),
    ("superlative_before_matrix_head", "Superlative before matrix head", "The thing I like most -> The most thing I like", "The thing I like most is apples.", "The most thing I like is apples.", "discourse"),
    ("double_obj_order", "Double obj order", "teach it to us -> teach us it", "She would teach it to us.", "She'd teach us it.", "discourse"),
    ("acomp_focusing_like", "Acomp focusing like", "It was really cheap -> It was like really cheap", "It was really cheap.", "It was like really cheap.", "discourse"),
    ("quotative_like", "Quotative like", "my friend said -> my friend was like", "And my friend said \"No way!\"", "And my friend was like \"No way!\"", "discourse"),
    # Extra (no eWAVE ID in code)
    ("got", "Got for have", "Present-tense have/has -> got", "I have a car.", "I got a car.", "verbal"),
    ("ass_pronoun", "Ass pronoun", "Pronoun camouflage / intensifier constructions", "That car is fast.", "That car is ass fast.", "discourse"),
]

def feature_to_json(fid: str, name: str, description: str, example_std: str, example_var: str, category: str) -> dict:
    return {
        "id": fid,
        "name": name,
        "description": description,
        "example_std": example_std,
        "example_var": example_var,
        "category": category,
        "dialects": ["aave", "indian_english", "pidgin", "chce", "caribbean", "southern_american", "appalachian", "british_nonstandard", "general_colloquial"],
        "requires_pos_tags": False,
        "tier": 1,
        "source": "eWAVE/Multi-VALUE",
    }

def main():
    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "shared" / "grammar_features.json"

    # Output exactly the 189 paper features (no merge with existing)
    features = [
        feature_to_json(fid, name, desc, std, var, cat)
        for fid, name, desc, std, var, cat in PAPER_FEATURES_189
    ]
    result = {"features": features}
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    print(f"Wrote {out_path}: {len(features)} grammar features (Ziems 189)")

if __name__ == "__main__":
    main()
